// Keep existing words in order: their indexes also identify saved stars and voice clips.
export const words = [
  { text: 'LUNE', picture: '🌙', syllables: 'lu · ne' },
  { text: 'VÉLO', picture: '🚲', syllables: 'vé · lo' },
  { text: 'ROSE', picture: '🌹', syllables: 'ro · se' },
  { text: 'POMME', picture: '🍎', syllables: 'pom · me' },
  { text: 'LAMA', picture: '🦙', syllables: 'la · ma' },
  { text: 'ROBOT', picture: '🤖', syllables: 'ro · bot' },
  { text: 'PIRATE', picture: '🏴‍☠️', syllables: 'pi · ra · te' },
  { text: 'TOMATE', picture: '🍅', syllables: 'to · ma · te' },
  { text: 'BANANE', picture: '🍌', syllables: 'ba · na · ne' },
  { text: 'TORTUE', picture: '🐢', syllables: 'tor · tue' },
  { text: 'SALADE', picture: '🥗', syllables: 'sa · la · de' },
  { text: 'ANANAS', picture: '🍍', syllables: 'a · na · nas' },
  { text: 'CHAT', picture: '🐱', syllables: 'chat' },
  { text: 'CHIEN', picture: '🐶', syllables: 'chien' },
  { text: 'LAPIN', picture: '🐰', syllables: 'la · pin' },
  { text: 'LION', picture: '🦁', syllables: 'lion' },
  { text: 'OURS', picture: '🐻', syllables: 'ours' },
  { text: 'PANDA', picture: '🐼', syllables: 'pan · da' },
  { text: 'KOALA', picture: '🐨', syllables: 'ko · a · la' },
  { text: 'POULE', picture: '🐔', syllables: 'pou · le' },
  { text: 'VACHE', picture: '🐮', syllables: 'va · che' },
  { text: 'CHEVAL', picture: '🐴', syllables: 'che · val' },
  { text: 'SOURIS', picture: '🐭', syllables: 'sou · ris' },
  { text: 'CANARD', picture: '🦆', syllables: 'ca · nard' },
  { text: 'SOLEIL', picture: '☀️', syllables: 'so · leil' },
  { text: 'NUAGE', picture: '☁️', syllables: 'nu · a · ge' },
  { text: 'ÉTOILE', picture: '⭐', syllables: 'é · toi · le' },
  { text: 'ARBRE', picture: '🌳', syllables: 'ar · bre' },
  { text: 'FLEUR', picture: '🌼', syllables: 'fleur' },
  { text: 'CERISE', picture: '🍒', syllables: 'ce · ri · se' },
  { text: 'POIRE', picture: '🍐', syllables: 'poi · re' },
  { text: 'KIWI', picture: '🥝', syllables: 'ki · wi' },
  { text: 'MELON', picture: '🍈', syllables: 'me · lon' },
  { text: 'CITRON', picture: '🍋', syllables: 'ci · tron' },
  { text: 'BALLON', picture: '🎈', syllables: 'bal · lon' },
  { text: 'LIVRE', picture: '📖', syllables: 'li · vre' },
];
